export const Users = [
  {
    id: 1,
    profilePicture: "person/1.jpeg",
    username: "Hamza",
  },
  {
    id: 2,
    profilePicture: "person/2.jpeg",
    username: "Ismail",
  },
  {
    id: 3,
    profilePicture: "person/3.jpeg",
    username: "Hazim",
  },
  {
    id: 4,
    profilePicture: "person/4.jpeg",
    username: "Saad",
  },
  {
    id: 5,
    profilePicture: "person/5.jpeg",
    username: "Sami",
  },
  {
    id: 6,
    profilePicture: "person/6.jpeg",
    username: "Usman",
  },
  {
    id: 7,
    profilePicture: "person/7.jpeg",
    username: "Danish",
  },
  {
    id: 8,
    profilePicture: "person/8.jpeg",
    username: "Aimal",
  },
  {
    id: 9,
    profilePicture: "person/9.jpeg",
    username: "Waseem",
  },
  {
    id: 10,
    profilePicture: "person/10.jpeg",
    username: "Abad",
  },
];

export const Posts = [
  {
    id: 1,
    desc: " Love For All, Hatred For None,",
    photo: "post/1.jpeg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    desc: " Love For All, Hatred For None,",
    photo: "post/2.jpeg",
    date: "5 mins ago",
    userId: 2,
    like: 32,
    comment: 49,
  },
  {
    id: 3,
    desc: " Love For All, Hatred For None,",
    photo: "post/3.jpeg",
    date: "5 mins ago",
    userId: 3,
    like: 32,
    comment: 9,
  },
  {
    id: 4,
    photo: "post/4.jpeg",
    date: "5 mins ago",
    userId: 4,
    like: 32,
    comment: 9,
  },
  {
    id: 5,
    photo: "post/5.jpeg",
    date: "51 mins ago",
    userId: 5,
    like: 32,
    comment: 9,
  },
  {
    id: 6,
    desc: " Love For All, Hatred For None,",
    photo: "post/6.jpeg",
    date: "51 mins ago",
    userId: 6,
    like: 3,
    comment: 129,
  },
  {
    id: 7,
    desc: " Love For All, Hatred For None,",
    photo: "post/7.jpeg",
    date: "1 mins ago",
    userId: 7,
    like: 132,
    comment: 89,
  },
  {
    id: 8,
    desc: " Love For All, Hatred For None,",
    photo: "post/8.jpeg",
    date: "5 mins ago",
    userId: 9,
    like: 52,
    comment: 99,
  },
  {
    id: 9,
    desc: " Love For All, Hatred For None,",
    photo: "post/9.jpeg",
    date: "10 mins ago",
    userId: 9,
    like: 44,
    comment: 2,
  },
];
